# version: '3.8'  # Pode ser removido se necessário

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - wordpress
      - metabase

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - mysql_data:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: userpassword
      WORDPRESS_DB_NAME: wordpress
    ports:
      - "8080:80"
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "8081:80"
    depends_on:
      - mysql

  metabase:
    image: metabase/metabase
    environment:
      MB_DB_TYPE: "mysql"
      MB_DB_HOST: "mysql"
      MB_DB_PORT: "3306"
      MB_DB_USER: "user"
      MB_DB_PASS: "userpassword"
      MB_DB_NAME: "metabase"
    ports:
      - "3000:3000"

volumes:
  mysql_data: